---
- name: Gather_facts
  hosts: test 
  become: yes
  gather_facts: true
  pre_tasks:
    - name: Get ansible_user home directory
      shell: 'getent passwd "{{ansible_user}}" | cut -d: -f6'
      register: ansible_home_result

    - name: Set the fact for the other scripts to use
      set_fact: ansible_home='{{ansible_home_result.stdout}}'
  tasks:
    - name: Show facts
      ansible.builtin.debug:
        var: ansible_facts
