---
- name: Windows基本設定
  hosts: windows
  roles:
    - role: git
      tags: git
    - role: alacritty
      tags: alacritty
    - role: chocolateygui
      tags: chocolateygui
    - role: obsidian
      tags: obsidian
