---
- name: Install neovim
  hosts: local
  become: yes
  pre_tasks:
    - name: Get ansible_user home directory
      shell: 'getent passwd "{{ansible_user}}" | cut -d: -f6'
      register: ansible_home_result

    - name: Set the fact for the other scripts to use
      set_fact: ansible_home='{{ansible_home_result.stdout}}'
  vars:
    xdg_cache_home: "{{ lookup('env', 'XDG_CACHE_HOME') | default(ansible_home + '/.cache', true) }}"
    xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_home + '/.config', true) }}"
    xdg_data_home: "{{ lookup('env', 'XDG_DATA_HOME') | default(ansible_home + '/.local/share', true) }}"
    xdg_state_home: "{{ lookup('env', 'XDG_STATE_HOME') | default(ansible_home + '/.local/state', true) }}"
    xdg_bin_home: "{{ lookup('env', 'XDG_BIN_HOME') | default(ansible_home + '/.local/bin', true) }}"
    tmp_dir: "{{ ansible_home }}/ansible-tmp"
  roles:
    - common
    - zellij
