---
- name: "Download k9s deb package"
  get_url:
    url: "https://github.com/derailed/k9s/releases/latest/download/k9s_linux_amd64.deb"
    dest: "{{ tmp_dir }}/k9s_linux_amd64.deb"
    mode: "644"
  when: ansible_facts['os_family'] == "Debian"

- name: "Install k9s"
  apt:
    deb: "{{ tmp_dir }}/k9s_linux_amd64.deb"
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: "Remove downloaded deb file"
  file:
    path: "{{ tmp_dir }}/k9s_linux_amd64.deb"
    state: "absent"
  when: ansible_facts['os_family'] == "Debian"

- name: "Install k9s(brew)"
  homebrew:
    name: "k9s"
  when: ansible_facts['os_family'] == "Darwin"
